// Minimal flat config for GJS / GNOME Shell extension code.
const gjsGlobals = {
    console: 'readonly',
    globalThis: 'readonly',
    imports: 'readonly',
    ARGV: 'readonly',
    global: 'readonly',
    log: 'readonly',
    logError: 'readonly',
    print: 'readonly',
    printerr: 'readonly',
    TextDecoder: 'readonly',
    TextEncoder: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
    Promise: 'readonly',
    Map: 'readonly',
    Set: 'readonly',
    Date: 'readonly',
    Math: 'readonly',
    Number: 'readonly',
    String: 'readonly',
    Object: 'readonly',
    Array: 'readonly',
    JSON: 'readonly',
    Error: 'readonly',
    Boolean: 'readonly',
    Symbol: 'readonly',
};

export default [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: gjsGlobals,
        },
        rules: {
            'no-unused-vars': ['error', {argsIgnorePattern: '^_'}],
            'no-undef': 'error',
            'prefer-const': 'error',
            'eqeqeq': ['error', 'always'],
            'no-var': 'error',
            'semi': ['error', 'always'],
            'quotes': ['error', 'single', {avoidEscape: true}],
            'indent': ['error', 4, {SwitchCase: 1, ignoredNodes: ['CallExpression > ClassExpression', 'CallExpression > ClassExpression *']}],
            'comma-dangle': ['error', 'always-multiline'],
            'no-trailing-spaces': 'error',
            'eol-last': 'error',
        },
    },
];
